# Generated by Django 5.1.6 on 2025-04-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_notification_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
    ]
