# Generated by Django 5.1.7 on 2025-05-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_max_capacity_event_required_materials_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="max_capacity",
            field=models.PositiveIntegerField(
                default=0, help_text="Put 0 for unlimited capacity"
            ),
        ),
    ]
