version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=unihub
      - POSTGRES_USER=unihubuser
      - POSTGRES_PASSWORD=unihubpass
      - DB_HOST=db
    networks:
      - unihub-network

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432" # added port to set up pgadmin connection
    environment:
      POSTGRES_DB: unihub
      POSTGRES_USER: unihubuser
      POSTGRES_PASSWORD: unihubpass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - unihub-network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: db-visualisation
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - unihub-network

networks:
  unihub-network:
    driver: bridge

volumes:
  postgres_data:
  media_volume:
