<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-04-07 09:37
=======
# Generated by Django 5.1.6 on 2025-04-23 03:28
>>>>>>> 5bdccc77ad62d8a0f71bd592a8784f09362a3ed6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
