# Generated by Django 5.1.6 on 2025-05-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_city_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='door_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='road',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
